### ISSUE TITLE
How to fill everything up to a border color?

### ISSUE THREAD

**Issue by vlxdev** [pavelkukov/q-floodfill#25]
Hi,
I'm trying to make a custom .isSameColor function that fills any pixel until it reaches a given color (I call it "border color").

My function returns true if the current pixel is different than the border color. I've also modified the .fill function so that it returns if the starting pixel has the border color. 

I've tried other variants as well, however, it's not working and I'm out of ideas.
I would appreciate it if you could point me in the right direction.

**Comment by pavelkukov** [comment]
Hi @vlxdev , I will take a look, but I'm not sure I fully understand your idea.
Please can you provide some example code!
You can use this [codepen ](https://codepen.io/pavelkukov/pen/abvYwdd) as a starter, if that works in your case.

**Comment by vlxdev** [comment]
Thanks for your quick reply!
I made a demo page [https://vlad-ui.firebaseapp.com/test-flood-fill/](https://vlad-ui.firebaseapp.com/test-flood-fill/)
I hope this clarifies what I'm trying to achieve.

**Comment by pavelkukov** [comment]
I've played a bit with this scenario, but it seems there is an underlying bug that leads to an infinite loop. 
Here is my codepen: https://codepen.io/pavelkukov/pen/ZEJJLWp?editors=0011
I need to debug and find a proper solution.

**Comment by pavelkukov** [comment]
Hi @vlxdev ,
I had some time to dig into this. The solution is to compare both, the border color and the fill color.
Here is a working demo: https://codepen.io/pavelkukov/pen/ZEJJLWp?editors=0010

This is because sometimes the algorithm has to check the color of an already filled line. But if the comparison function checks only the predefined border, it loops infinitely. Fill color is not taken into consideration and an already filled line gets queued over and over.

An alternative solution also could be to keep track of already filled pixels, but this can increase memory consumption and significantly slow down the algorithm. So the best way to ignore all colors but the target is to check the target color + fill color as per the example.

Best,
Pavel

**Comment by vlxdev** [comment]
I understand. Thank you very much @pavelkukov for looking into it!
